import type { Metadata } from "next";
import { Bricolage_Grotesque, Noto_Sans_JP, DM_Sans } from "next/font/google";
import "./globals.css";

const bricolageGrotesque = Bricolage_Grotesque({
  weight: ['400', '800'],
  display: 'swap',
  preload: false,
  variable: '--bricolage-grotesque'
});

const notoSansJP = Noto_Sans_JP({
  weight: ['400', '700'],
  display: 'swap',
  preload: false,
  variable: '--noto-sans-jp'
});

const dMSans = DM_Sans({
  weight: '400',
  display: 'swap',
  preload: false,
  variable: '--dm-sans'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${bricolageGrotesque.variable} ${notoSansJP.variable} ${dMSans.variable}`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
